export const questionType = {
  BUTTON_SINGLE_CHOICE: 'BUTTON_SINGLE_CHOICE',
  VIDEO: 'VIDEO',
  TEXT: 'TEXT',
  MULTIPLE_CHOICE: 'MULTIPLE_CHOICE',
  CUSTOM: 'CUSTOM',
  BUTTON_SINGLE_CHOICE_DESCRIPTION: 'BUTTON_SINGLE_CHOICE_DESCRIPTION',
}
const questions = [
  {
    code: 'Q001'
  }
]